{{ if .Values.modules.istio.enabled }}
{{ $isMaster := eq .Values.global.cluster "master" }}
{{ $prefix := printf "%s-%s" .Values.global.clusterNamespace .Values.global.clusterName }}
{{ $module := "istio" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    cluster: {{ ternary "master" $prefix $isMaster }}
  name: {{ ternary $module (printf "%s-%s" $prefix $module) $isMaster }}
  namespace: argocd
spec:
  destination:
    name: {{ .Values.global.clusterName }}
    namespace: istio-system
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
        - name: modules.istio-namespace.enabled
          value: {{ .Values.modules.istio.enabled }}
        - name: modules.istio-namespace.autoSync
          value: {{ .Values.modules.istio.autoSync }}
        - name: modules.istio-base.enabled
          value: {{ .Values.modules.istio.enabled }}
        - name: modules.istio-base.autoSync
          value: {{ .Values.modules.istio.autoSync }}
        - name: modules.istio-istiod.enabled
          value: {{ .Values.modules.istio.enabled }}
        - name: modules.istio-istiod.logLevel
          value: {{ .Values.modules.istio.logLevel }}
        - name: modules.istio-istiod.autoSync
          value: {{ .Values.modules.istio.autoSync }}
        - name: modules.istio-gateway.enabled
          value: {{ .Values.modules.istio.enabled }}
        - name: modules.istio-gateway.autoSync
          value: {{ .Values.modules.istio.autoSync }}
        - name: spec.source.repoURL
          values: {{ .Values.spec.source.repoURL }}
        - name: spec.source.targetRevision
          values: {{ .Values.spec.source.targetRevision}}
        - name: spec.project
          values: {{ .Values.spec.project }}
        - name: global.cluster
          value: {{ .Values.global.cluster }}
        - name: global.clusterName
          value: {{ .Values.global.clusterName }}
        - name: global.clusterNamespace
          value: {{ .Values.global.clusterNamespace }}
        - name: global.privateRegistry
          value: {{ .Values.global.privateRegistry }}
        - name: global.network.disabled
          value: "{{ .Values.global.network.disabled }}"
    path: manifest/istio-bootstrap
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
{{ end }}
