{{ if .Values.modules.istio.enabled }}
{{ $isMaster := eq .Values.global.cluster "master" }}
{{ $prefix := printf "%s-%s" .Values.global.clusterNamespace .Values.global.clusterName }}
{{ $module := "istio" }}
{{ $ns := "ns-istio-system" }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-app-set
  namespace: argocd
spec:
  generator:
    template:
      metadata:
        name: istio-app
      spec:
        destination:
          name: {{ .Values.global.clusterName }}
        project: {{ .Values.spec.project }}
        syncPolicy:
          automated:
            selfHeal: true
            prune: true
          syncOptions:
            - ApplyOutOfSyncOnly=true
        source:
          repoURL: {{ .Values.spec.source.repoURL }}
          targetRevision: {{ .Values.spec.source.targetRevision }}
        helm:
          releaseName: {{ $module }}
  applications:
    - name: ns-istio-system
      source:
        path: manifest/istio/namespace
      syncPolicy:
        syncWave: -3
    - name: istio-base
      source:
        path: manifest/istio/istio-base
        namespace: istio-system
      syncPolicy:
        syncWave: -2
        preSync:
          hook:
            group: argocd.argoproj.io
            version: v1alpha1
            kind: PreSyncHook
            metadata:
              name: istio-pre-sync
            spec:
              command: ['bash', '-c', 'echo "Running pre-sync hook for istio-base"']
    - name: istio-istiod
      source:
        path: manifest/istio/istio-istiod
        namespace: istio-system
      syncPolicy:
        syncWave: -1
        preSync:
          hook:
            group: argocd.argoproj.io
            version: v1alpha1
            kind: PreSyncHook
            metadata:
              name: istio-istiod-pre-sync
            spec:
              command: ['bash', '-c', 'echo "Running pre-sync hook for istio-istiod"']
    - name: istio-gateway
      source:
        path: manifest/istio/istio-gateway
        namespace: istio-system
      syncPolicy:
        syncWave: 0
